services:

  postgres:
    image: postgres:18
    container_name: postgres
    ports:
      - "6000:6000"
    restart: unless-stopped
    env_file:
      - ./Central_Hospital/Data_Base/.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: America/Santiago
    command: -p 6000
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/pgdata
      - ./Central_Hospital/Data_Base/init_test.sql:/docker-entrypoint-initdb.d/init_test.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 6000" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hospital_network

  authentication:
    image: authentication_service
    build: ./Central_Hospital/Authentication
    container_name: authentication_service
    ports:
      - "7050:7050"
    environment:
      - TZ=America/Santiago
    env_file:
      - ./Central_Hospital/Authentication/.env
    networks:
      - hospital_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  alert_system:
    image: alert_system
    build: ./Central_Hospital/Alert_System
    container_name: alert_system
    ports:
      - "7030:7030"
    environment:
      - TZ=America/Santiago
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=6000
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    env_file:
      - ./Central_Hospital/Alert_System/.env
    networks:
      - hospital_network
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: unless-stopped
  reporting_service:
    image: reporting_service
    build: ./Central_Hospital/Reporting_service
    container_name: reporting_service
    ports:
      - "7020:7020"
    environment:
      - TZ=America/Santiago
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=6000
    env_file:
      - ./Central_Hospital/Reporting_service/.env
    networks:
      - hospital_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - hospital_network

  frontend_central:
    image: frontend_central
    build: ./frontend-central
    container_name: frontend_central
    ports:
      - "8020:8020"
    environment:
      - TZ=America/Santiago
    restart: unless-stopped
    networks:
      - hospital_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - TZ=America/Santiago
    networks:
      - hospital_network
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  hospital_network:
    driver: bridge

volumes:
  postgres_data:
