services:

  inventory_service:
    image: inventory_service
    build: ./Departamento/Inventory_Service
    container_name: inventory_service
    ports:
      - "7010:7010"
    environment:
      - TZ=America/Santiago
    env_file:
      - ./Departamento/.env
    restart: unless-stopped
    networks:
      - hospital_network

  frontend_nodo:
    image: frontend_nodo
    build: ./frontend-nodo
    container_name: frontend_nodo
    ports:
      - "8010:8010"
    environment:
      - TZ=America/Santiago
    restart: unless-stopped
    networks:
      - hospital_network

networks:
  hospital_network:
    driver: bridge
