services:

  postgres:
    image: postgres:18
    container_name: postgres
    ports:
      - "6000:6000"
    restart: unless-stopped
    environment:
      POSTGRES_DB: gestion_hospitalario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: America/Santiago
    command: -p 6000
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/pgdata
      - ./Central_Hospital/Data_Base/init_test.sql:/docker-entrypoint-initdb.d/init_test.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 6000" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hospital_network

networks:
  hospital_network:
    driver: bridge

volumes:
  postgres_data:
