services:

  inventory_service:
    image: inventory_service
    build: ./Departamento/Inventory_Service
    container_name: inventory_service
    ports:
      - "7010:7010"
    environment:
      - TZ=America/Santiago
    env_file:
      - ./Departamento/.env
    restart: unless-stopped
    networks:
      - hospital_network

  supplies_registry:
    image: supplies_registry
    build:
      context: ./Departamento/Supplies_Registry
      args:
        NEXT_PUBLIC_DEPARTMENT_ID: ${DEPARTMENT_ID:-2}
        NEXT_PUBLIC_AUTH_API_BASE: ${NEXT_PUBLIC_AUTH_API_BASE:-http://localhost:7050/api/v1/auth}
    container_name: supplies_registry
    ports:
      - "8010:8010"
    environment:
      - TZ=America/Santiago
    env_file:
      - ./Departamento/.env
    restart: unless-stopped
    networks:
      - hospital_network

networks:
  hospital_network:
    driver: bridge
