// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/reports/active-alerts": {
            "get": {
                "description": "Returns all active alerts for the specified department",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get active alerts report",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Department ID",
                        "name": "department_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ActiveAlertReport"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reports/critical-stock": {
            "get": {
                "description": "Returns supplies with quantity \u003c= minimum stock for the specified department",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get critical stock report",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Department ID",
                        "name": "department_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CriticalStockReport"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reports/monthly-consumption": {
            "get": {
                "description": "Returns the total quantity of consumed supplies in the last 30 days for the specified department",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get monthly consumption report",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Department ID",
                        "name": "department_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MonthlyConsumptionReport"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reports/traceability": {
            "get": {
                "description": "Returns the movement history of a specific supply in the specified department",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get traceability report for a supply",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Department ID",
                        "name": "department_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Supply Internal Code",
                        "name": "supply_code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TraceabilityReport"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ActiveAlertReport": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "supply_name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.CriticalStockReport": {
            "type": "object",
            "properties": {
                "current_stock": {
                    "type": "number"
                },
                "department": {
                    "type": "string"
                },
                "internal_code": {
                    "type": "string"
                },
                "minimum_stock": {
                    "type": "number"
                },
                "supply_name": {
                    "type": "string"
                }
            }
        },
        "models.MonthlyConsumptionReport": {
            "type": "object",
            "properties": {
                "internal_code": {
                    "type": "string"
                },
                "supply_name": {
                    "type": "string"
                },
                "total_consumed": {
                    "type": "number"
                }
            }
        },
        "models.TraceabilityReport": {
            "type": "object",
            "properties": {
                "destino": {
                    "type": "string"
                },
                "movement_date": {
                    "type": "string"
                },
                "observations": {
                    "type": "string"
                },
                "origen": {
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "responsable": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7020",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Reporting Service API",
	Description:      "Backend service for generating department inventory reports",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
