// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/inventory/movements": {
            "post": {
                "description": "Registers a general movement in the inventory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Register an inventory movement",
                "parameters": [
                    {
                        "description": "Movement data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.MovementRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Movement successfully registered",
                        "schema": {
                            "$ref": "#/definitions/schemas.OperationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/inventory/categories": {
            "get": {
                "description": "Returns all supply categories",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get supply categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SupplyCategory"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/inventory/departments/stock": {
            "get": {
                "description": "Returns the stock of the configured department",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get department stock",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.DepartmentInventory"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Modifies the stock of a supply for a specific department (increase or decrease)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Modify department stock",
                "parameters": [
                    {
                        "description": "Stock modification data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.StockModificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "schema": {
                            "$ref": "#/definitions/schemas.OperationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Department or supply not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/inventory/movements": {
            "get": {
                "description": "Returns all inventory movements for the configured department",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get inventory movements",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.InventoryMovement"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/inventory/supplies": {
            "get": {
                "description": "Returns all supplies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get supplies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Supply"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Department": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "inventory": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DepartmentInventory"
                    }
                },
                "isActive": {
                    "type": "boolean"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.DepartmentInventory": {
            "type": "object",
            "properties": {
                "department": {
                    "$ref": "#/definitions/models.Department"
                },
                "departmentID": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "number"
                },
                "supply": {
                    "$ref": "#/definitions/models.Supply"
                },
                "supplyID": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.InventoryMovement": {
            "type": "object",
            "properties": {
                "destinationDepartment": {
                    "$ref": "#/definitions/models.Department"
                },
                "destinationDepartmentID": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "movementDate": {
                    "type": "string"
                },
                "observations": {
                    "type": "string"
                },
                "originDepartment": {
                    "$ref": "#/definitions/models.Department"
                },
                "originDepartmentID": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "number"
                },
                "supply": {
                    "$ref": "#/definitions/models.Supply"
                },
                "supplyID": {
                    "type": "integer"
                },
                "type": {
                    "description": "e.g. \"entrada\", \"salida\", \"transferencia\"",
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "models.Supply": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/models.SupplyCategory"
                },
                "categoryID": {
                    "type": "integer"
                },
                "departmentInventory": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DepartmentInventory"
                    }
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "internalCode": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "minimumStock": {
                    "type": "number"
                },
                "movements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.InventoryMovement"
                    }
                },
                "name": {
                    "type": "string"
                },
                "unitOfMeasure": {
                    "type": "string"
                }
            }
        },
        "models.SupplyCategory": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "supplies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Supply"
                    }
                }
            }
        },
        "schemas.MovementRequest": {
            "type": "object",
            "required": [
                "destination_department_id",
                "origin_department_id",
                "quantity",
                "supply_id",
                "user_id"
            ],
            "properties": {
                "destination_department_id": {
                    "type": "integer"
                },
                "observations": {
                    "type": "string"
                },
                "origin_department_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "number"
                },
                "supply_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "schemas.OperationResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "movement_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "schemas.StockModificationRequest": {
            "type": "object",
            "required": [
                "quantity_change",
                "supply_id",
                "user_id"
            ],
            "properties": {
                "observations": {
                    "type": "string"
                },
                "quantity_change": {
                    "type": "number"
                },
                "supply_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7010",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Inventory Service API",
	Description:      "API for the Hospital's inventory management.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
